
@itemId = 60acd24bb88a524f5e0bd5e0
@itemId1 = 60acd24bb88a524f5e0bd5e0
@userId = 60acd712b9409f51d8e677a4
@inventoryItemId = 60acd77eb9409f51d8e677a8
###

GET http://localhost:4000/api/items/

###

GET http://localhost:4000/api/items/{{itemId}}

###
POST http://localhost:4000/api/{{userId}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0

{
  "quantity": "2",
  "expiryDate": "06-06-2021"
}
###
POST http://localhost:4000/api/{{userId}}/items/{{itemId1}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFjZDcxMmI5NDA5ZjUxZDhlNjc3YTQiLCJpYXQiOjE2MjE5NDAwMTksImV4cCI6MTYyMjE5OTIxOX0.IsdcLNFYOHQsXVqrrrTPyQbsltZiqdb3S-AJURXWMBk

{
  "quantity": "1",
  "expiryDate": "06-06-2025"
}

###
GET http://localhost:4000/api/{{userId}}/items/{{inventoryItemId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFjZDcxMmI5NDA5ZjUxZDhlNjc3YTQiLCJpYXQiOjE2MjE5NDAwMTksImV4cCI6MTYyMjE5OTIxOX0.IsdcLNFYOHQsXVqrrrTPyQbsltZiqdb3S-AJURXWMBk

###
GET http://localhost:4000/api/{{userId}}/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0
###

DELETE http://localhost:4000/api/{{userId}}/items/{{inventoryItemId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFjZDcxMmI5NDA5ZjUxZDhlNjc3YTQiLCJpYXQiOjE2MjE5NDAwMTksImV4cCI6MTYyMjE5OTIxOX0.IsdcLNFYOHQsXVqrrrTPyQbsltZiqdb3S-AJURXWMBk

###

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "abubakar1",
  "password": "pass",
  "email": "abubakar1@email.com",
  "addressDetails": {
      "postalCode": "54321",
      "city": "London",
      "street": "Downing Street",  
      "streetNo": "10",
      "region": "United Kingdom",
      "country": "England"
  }
}

###

POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "abubakar1@email.com",
  "password": "pass"
}

