
@itemId = 60abab29248393b5b9dfea37
@itemId1 = 60abab29248393b5b9dfea38
@userId = 60abab29248393b5b9dfea33
###

GET http://localhost:4000/api/items/

###

GET http://localhost:4000/api/items/{{itemId}}

###
POST http://localhost:4000/api/{{userId}}/items/{{itemId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0

{
  "quantity": "2",
  "expiryDate": "06-06-2021"
}
###
POST http://localhost:4000/api/{{userId}}/items/{{itemId1}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0

{
  "quantity": "1",
  "expiryDate": "06-06-2025"
}

###
GET http://localhost:4000/api/{{userId}}/items/60ababe56cbe33b5d1891381
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0

###
GET http://localhost:4000/api/{{userId}}/items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFiYWIyOTI0ODM5M2I1YjlkZmVhMzMiLCJpYXQiOjE2MjE4NjMzMDEsImV4cCI6MTYyMjEyMjUwMX0.KHGBqcOBV_xXjEPBLJJa2kCT0qX8mBUicgB_KHHsoJ0
###

DELETE http://localhost:4000/api/{{userId}}/items/{{inventoryId}}
Authorization: Bearer 

###

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "abubakar1",
  "password": "pass",
  "email": "abubakar1@email.com",
  "addressDetails": {
      "postalCode": "54321",
      "city": "London",
      "street": "Downing Street",  
      "streetNo": "10",
      "region": "United Kingdom",
      "country": "England"
  }
}

###

POST http://localhost:4000/api/login
content-type: application/json

{
  "email": "jonas@jonas.com",
  "password": "jonas"
}

